const livroAbreviacoes = {
    "gênesis": "gn",
    "êxodo": "ex",
    "levítico": "lv",
    "números": "nm",
    "deuteronômio": "dt",
    "josué": "js",
    "juízes": "jz",
    "rute": "rt",
    "1 samuel": "1sm",
    "2 samuel": "2sm",
    "1 reis": "1rs",
    "2 reis": "2rs",
    "1 crônicas": "1cr",
    "2 crônicas": "2cr",
    "esdras": "ed",
    "neemias": "ne",
    "ester": "et",
    "jó": "jó",
    "salmos": "sl",
    "provérbios": "pv",
    "eclesiastes": "ec",
    "cânticos": "ct",
    "isaías": "is",
    "jeremias": "jr",
    "lamentações": "lm",
    "ezequiel": "ez",
    "daniel": "dn",
    "oseias": "os",
    "joel": "jl",
    "amós": "am",
    "obadias": "ob",
    "jonas": "jn",
    "miquéias": "mq",
    "naum": "na",
    "habacuque": "hc",
    "sofonias": "sf",
    "ageu": "ag",
    "zacarias": "zc",
    "malaquias": "ml",
    "mateus": "mt",
    "marcos": "mc",
    "lucas": "lc",
    "joão": "jo",
    "atos": "at",
    "romanos": "rm",
    "1 coríntios": "1co",
    "2 coríntios": "2co",
    "gálatas": "gl",
    "efésios": "ef",
    "filipenses": "fp",
    "colossenses": "cl",
    "1 tessalonicenses": "1ts",
    "2 tessalonicenses": "2ts",
    "1 timóteo": "1tm",
    "2 timóteo": "2tm",
    "tito": "tt",
    "filemom": "fm",
    "hebreus": "hb",
    "tiago": "tg",
    "1 pedro": "1pe",
    "2 pedro": "2pe",
    "1 joão": "1jo",
    "2 joão": "2jo",
    "3 joão": "3jo",
    "judas": "jd",
    "apocalipse": "ap"
};
